
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/home/aminya/cmake/cmake-3.26.4-linux-x86_64/share/cmake-3.26/Modules/CMakeDetermineSystem.cmake:204 (message)"
      - "CMakeLists.txt:6 (project)"
    message: |
      The system is: Linux - 6.2.0-34-generic - x86_64
...

---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake-3.27/Modules/CMakeDetermineSystem.cmake:211 (message)"
      - "CMakeLists.txt:6 (project)"
    message: |
      The system is: Linux - 6.2.0-36-generic - x86_64
...

---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineSystem.cmake:233 (message)"
      - "CMakeLists.txt:6 (project)"
    message: |
      The system is: Linux - 6.2.0-39-generic - x86_64
...

---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineSystem.cmake:233 (message)"
      - "CMakeLists.txt:6 (project)"
    message: |
      The system is: Linux - 6.5.0-21-generic - x86_64
...
