
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/home/aminya/cmake/cmake-3.26.4-linux-x86_64/share/cmake-3.26/Modules/CMakeDetermineSystem.cmake:204 (message)"
      - "CMakeLists.txt:6 (project)"
    message: |
      The system is: Linux - 6.2.0-34-generic - x86_64
...
