# https://taskfile.dev/#6/installation
version: 3

# Run before install pip deps
#   python -m venv ./.venv
#   source ./.venv/bin/activate

tasks:
  readme:
    - pipx install pandoc-include
    # requires pandoc 3.0.0 or higher
    - pandoc -s --filter pandoc-include -o ../README.md ./README.md

  docs:
    deps:
      - readme
    cmds:
      - |
        pip install GitPython sphinx-rtd-theme breathe sphinx-sitemap sphinxcontrib-moderncmakedomain myst-parser
        cmake -S ./ -B ./build -G "Ninja Multi-Config" -DCMAKE_BUILD_TYPE=Release
        cmake --build ./build --config Release
        touch ./build/.nojekyll
        rm -rf ./build/*.ninja ./build/*log ./build/*.py ./build/CMakeFiles ./build/CMakeCache.txt ./build/*.cmake

  docs.preview:
    deps:
      - docs
    cmds:
      - cd ./build/html && npx servor --browse

  docs.deploy:
    deps:
      - docs
    cmds:
      - npx -y gh-pages -d ./build/ -t true
